### GET request to get all elements
GET http://localhost:8080/sammlungsItems
Accept: application/json

### GET request to get all a specific element by id (http://localhost:8080/sammlungsItems/<id>)
GET http://localhost:8080/sammlungsItems/36
Accept: application/json

###

