spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./devDb;AUTO_SERVER=TRUE
    username: sa
    password: ""
hibernate:
  hbm2ddl:
    auto: update
  dialect:  org.hibernate.dialect.H2Dialect
logging:
  level:
    org.springframework: DEBUG

